"""empty message

Revision ID: 10a1704bd70f
Revises: 2ee5a44e0509
Create Date: 2022-06-16 09:13:29.639986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a1704bd70f'
down_revision = '2ee5a44e0509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_info',
    sa.Column('domain_name', sa.String(length=64), nullable=False),
    sa.Column('cus_name', sa.String(length=64), nullable=True),
    sa.Column('cus_email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('domain_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_info')
    # ### end Alembic commands ###
