"""empty message

Revision ID: 2ee5a44e0509
Revises: 
Create Date: 2022-06-14 10:37:09.924576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ee5a44e0509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_index', table_name='domains')
    op.drop_table('domains')
    op.drop_index('namealgoindex', table_name='tsigkeys')
    op.drop_table('tsigkeys')
    op.drop_index('domainidindex', table_name='cryptokeys')
    op.drop_table('cryptokeys')
    op.drop_table('supermasters')
    op.drop_index('domainmetadata_idx', table_name='domainmetadata')
    op.drop_table('domainmetadata')
    op.drop_table('comments')
    op.drop_index('nametype_index', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=64000), nullable=True),
    sa.Column('ttl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('prio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('disabled', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ordername', mysql.VARCHAR(charset='latin1', collation='latin1_bin', length=255), nullable=True),
    sa.Column('auth', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('nametype_index', 'records', ['name', 'type'], unique=False)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('modified_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('account', mysql.VARCHAR(charset='utf8mb3', length=40), nullable=True),
    sa.Column('comment', mysql.TEXT(charset='utf8mb3'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('domainmetadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kind', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('domainmetadata_idx', 'domainmetadata', ['domain_id', 'kind'], unique=False)
    op.create_table('supermasters',
    sa.Column('ip', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('nameserver', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account', mysql.VARCHAR(charset='utf8mb3', length=40), nullable=False),
    sa.PrimaryKeyConstraint('ip', 'nameserver'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('cryptokeys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('flags', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('domainidindex', 'cryptokeys', ['domain_id'], unique=False)
    op.create_table('tsigkeys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('algorithm', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('secret', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('namealgoindex', 'tsigkeys', ['name', 'algorithm'], unique=False)
    op.create_table('domains',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('master', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last_check', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('notified_serial', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account', mysql.VARCHAR(charset='utf8mb3', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name_index', 'domains', ['name'], unique=False)
    # ### end Alembic commands ###
