"""empty message

Revision ID: f79d57dd471a
Revises: 10a1704bd70f
Create Date: 2022-06-16 09:24:19.109141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79d57dd471a'
down_revision = '10a1704bd70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('cus_name', sa.String(length=64), nullable=True),
    sa.Column('cus_email', sa.String(length=64), nullable=True),
    sa.Column('cus_phone', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_info')
    # ### end Alembic commands ###
